### PR TITLE
Remove full tests from CIs

### LINKED ISSUE #77: Avoid CIs from downloading large amount of data
**Description of the desired feature**

CIs now download all files in registry while running tests and building the gallery.

After new datasets will be included into Rockhound, the amount of data needed to be fetched may grow too large that CIs may be not be capable of finishing the testing builds.
Because there's no way to permanently store this datasets on the CIs, we decided to remove test and gallery builds from being run on by the CIs. Instead, the maintainers should run the tests and build the gallery locally before each PR is merged into `master`. Test functions and gallery examples must still be included on every new PR (and 100% coverage is still a goal to achieve), but the difference is that CIs won't run them.
All files inside `doc/gallery` should be pushed to the repository so CIs can still build the docs (and deploy them) but avoiding to rerun the gallery examples.
A new minimal test function should be added that only checks if all files in the registry are available for download.
Add an extra point to PR checklist to remind contributors to build the gallery example and push any change on `doc/gallery`, and maintainers to run all tests before merging the PR.

**Are you willing to help implement and maintain this feature?** Yes

### PR DESCRIPTION
**Pull request by santisoler**
Add minimal test function that checks if all files in registry are available
for download. Run only style checks on Azure Pipelines. Run only a single
Travis CI configuration with Python 3.6 that runs the minimal test, style
checks and deploys documentation and releases to PyPI. Remove uploading
coverage to Codecov. Remove `doc/gallery` form `.gitignore`. Add all files
inside `gallery/doc`. Create new targets for `doc/Makefile`: `html-noplot`,
`gallery` and `clean-gallery`. The first one builds the website without running
examples, the second one runs the examples and builds the website, the third
one cleans doc/gallery directory. Change default target `all` to `html-noplot`.
Update Pull Request template from `fatiando/.github` and add new remainders for
contributors to build the docs and push changes on `doc/gallery`, and for
maintainers to run all tests before merging the PR.

Fixes #77

**Reminders**

- [ ] Run `make format` and `make check` to make sure the code follows the style guide.
- [ ] Add tests for new features or tests that would have caught the bug that you're fixing.
- [ ] Add new public functions/methods/classes to `doc/api/index.rst`.
- [ ] Write detailed docstrings for all functions/methods.
- [ ] If adding new functionality, add an example to the docstring, gallery, and/or tutorials.

### CODE REVIEW

**Comment by santisoler** [comment]
@leouieda Should we also remove the `.codecov.yml` file?

**Comment by leouieda** [comment]
Yeah, if we're not running the tests on CI then it's kind of useless.

**Comment by leouieda** [comment]
We'll also need to remove the requirements for coverage from the PR status checks.

**Review by leouieda — APPROVED** [review]
Looks good to me @santisoler. Seems to be running OK but we might be surprised once we merge :slightly_smiling_face:

**Comment by leouieda** [comment]
@santisoler I'm going to push the updates to the travis config here to see if we can trigger the build.

**Comment by santisoler** [comment]
Thanks Leo!

**Comment by santisoler** [comment]
@leouieda I've modified some targets in `doc/Makefile`. By default it will not run the gallery examples. I have added two more targets:
- `gallery`: for running the gallery and building the entire website.
- `clean-gallery`: for removing the `doc/gallery` directory.

What do you think about this?

**Comment by leouieda** [comment]
So to build the docs for a new gallery plot we'd have to run `make gallery` only? Is that needed actually? Wouldn't sphinx-gallery know not to rebuild the examples since they are in the repository already?

**Comment by santisoler** [comment]
> So to build the docs for a new gallery plot we'd have to run make gallery only? Is that needed actually? Wouldn't sphinx-gallery know not to rebuild the examples since they are in the repository already?

Yes, `sphinx-gallery` would know not to build the gallery examples *if the built files are in `doc/gallery`*. If we are opening a PR with a new example but we haven't built the gallery yet, then the CIs will try to build them, and we want to avoid that. That's why I though it would be better to explicitly instruct CIs not to build the examples.

**Comment by leouieda** [comment]
Ah right, as always you saw something I overlooked :slightly_smiling_face: Did I ever mention that I'm really glad you got on board?

OK, then I fully agree with the idea of separating the gallery plot.

**Pull request merged**
